version: '2'
services:
  testcontainersampleproject-app:
    image: testcontainersampleproject
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://testcontainersampleproject-mysql:3306/testcontainersampleproject?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://testcontainersampleproject-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://testcontainersampleproject-elasticsearch:9200
    ports:
      - 8080:8080
  testcontainersampleproject-mysql:
    extends:
      file: mysql.yml
      service: testcontainersampleproject-mysql
  testcontainersampleproject-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: testcontainersampleproject-elasticsearch
